### ISSUE TITLE
Screen flicking when select a address from search result list

### ISSUE THREAD

**Issue by moon-jerry** [twho/material-design-searchbar-ios#6]
The issue was textFieldDidEndEditing getting called multiple times, cause the function 'viewMovedown' gets called multiple times -> animation multiple times. 

Solution,

fire endEditing event only once, what I did was comment out code below in private func didSelectPlacemark()

//self.searchbar.textFieldDidEndEditing(self.searchbar.textInput)
 // Dismiss search results view
 //self.showSearchResultsView(false) //

then add self.searchbar.endEditing(true) in 

 // Configure searchResultsView
        searchResultsView = SearchResultsView(didSelectAction: { [weak self] (placemark) in
            guard let self = self else { return }
            self.didSelectPlacemark(placemark)
            self.searchbar.endEditing(true)
 })

let me know if you want me push the changes.

**Comment by twho** [comment]
Sure, please make a PR, thanks!

**Comment by twho** [comment]
Thanks for your contribution, I've applied your fix and rewrite animation logics.
